# Site settings
title: JulieISBaka
baseurl: "/Julieisbaka"

# Navigation structure
nav:
  - title: Home
    url: "{{ site.baseurl }}"
  - title: Code of Conduct
    url: "{{ site.baseurl }}/CODE_OF_CONDUCT.html"
  - title: Contributing
    url: "{{ site.baseurl }}/CONTRIBUTING.html"
  - title: License
    url: "{{ site.baseurl }}/LICENSE.html"
  - title: Security
    url: "{{ site.baseurl }}/SECURITY.html"