# Site settings
title: JulieISBaka

# Navigation structure
nav:
  - title: Home
    url: /Julieisbaka
  - title: Code of Conduct
    url: /Julieisbaka/CODE_OF_CONDUCT.html
  - title: Contributing
    url: /Julieisbaka/CONTRIBUTING.html
  - title: License
    url: /Julieisbaka/LICENSE.html
  - title: Security
    url: /Julieisbaka/SECURITY.html